# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        steps:
          - run:
              name: Install npm
              command: npm ci
          - run:
              name: Run build
              command: npm run build
      deploy:
        docker:
          - image: circleci/python:3.7-stretch
        working_directory: ~/circleci-docs
        steps:
          - run:
              name: Install awscli
              command: sudo pip install awscli
          - run:
              name: Deploy to S3
              command: aws s3 sync ./build/ s3://breakdownstress --delete

    workflows:
      version: 2
      build-deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
              filters:
                branches:
                  only: master
